version: "2"

run:
  tests: true
  skip-dirs-use-default: true

output:
  format: colored-line-number

formatters:
  enable:
    - gofmt

linters:
  enable:
    - govet
    - errcheck
    - staticcheck

    - ineffassign
    - unused

linters-settings:
  funlen:
    lines: 40
    statements: 30